version: '3.8'

services:
  postgres:
    container_name: ticket-postgres
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: zixpay
        PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
